### ISSUE TITLE
czym uzywac 

### ISSUE THREAD

**Issue by taurynamonsterxdd** [xShadyy/CS2-Bhop-Config#1]
siema czym lepiej skakac na skrolu guzik na myszcze czy co pozdr

**Comment by xShadyy** [comment]
> siema czym lepiej skakac na skrolu guzik na myszcze czy co pozdr

Najlepiej na scroolu, jak chcesz robić dluższe, pojedyńcze jumpy to zbinduj sobie na Mouse5 alias 'Jb'
